name: ci

on:
  push:
    branches:
      - "main"

jobs:
  Build-image-to-DockerHub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:latest
  
  Deploy-on-K8s-Cluster:
    needs: [Build-image-to-DockerHub]
    runs-on: ubuntu-latest
    env:
      nodePort: 30800
    steps:
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Deploy
        run: |
          helm repo add my-fastapi-template https://john19968010.github.io/my-helm-chart/helm-chart-index && \
          helm install my-my-fastapi-chart my-fastapi-template/my-fastapi-chart --version 0.1.0 \
          --set service.nodePort=$nodePort